name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
  - TheSingleOneYT
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: type
    attributes:
      label: Bug Type
      description: What type of issue is this?
      options:
        - Exception thrown (did an error box appear?)
        - Crash (did the software disappear?)
        - Function error (did the software do something different than expected?)
        - Unresponsive error (did the software stop responding?)
        - Other (none of the other options describe my problem)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
    validations:
      required: true
  - type: textarea
    id: what-version
    attributes:
      label: What version?
      description: What version of our software were you running?
      placeholder: Current.
      value: "Current version."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Ready to submit?
      description: Please double check to see if this issue is being worked on already and you have provided as much detail as possible.
        - label: I have checked my issue submission
          required: true
